BosvogelWebPlatform/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('agenda/', include('apps.agenda.urls')),
                  path('leiding/', include('apps.leiding.urls')),
                  path('verhuur/', include('apps.rent.urls')),
                  path('takken/', include('apps.takken.urls')),
                  path('', include('apps.home.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/agenda/urls.py
from django.urls import path

from . import views

app_name = 'agenda'
urlpatterns = [
    path('', views.index, name='index'),
    path('alle-vergaderingen', views.index, {'all_vergaderingen': 'True'}, name='index_all_vergaderingen')
]

apps/agenda/models.py
from django.db import models

from apps.home.constants import Takken, Events
from apps.place.models import Place


def dangling_rental_event_count():
    return Event.rentals.filter(reservation=None).count()


class RentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type=Events.RENTAL)

    def new_rental(self, start_date, end_date, event_name):
        return self.create(
            name=event_name,
            startDate=start_date,
            endDate=end_date,
            startTime=Events.DEFAULT_RENT_START_TIME,
            endTime=Events.DEFAULT_RENT_ENDING_TIME,
            type=Events.RENTAL
        )

    def is_available_for_rent(self, start_date, end_date):
        if self.get_queryset().filter(startDate__exact=start_date, endDate__exact=end_date):
            return False
        elif self.get_queryset().filter(startDate__lte=start_date, endDate__gt=end_date).exists():
            return False
        elif self.get_queryset().filter(startDate__gt=start_date, endDate__lt=end_date).exists():
            return False
        elif self.get_queryset().filter(startDate__gt=start_date, startDate__lt=end_date).exists():
            return False
        elif self.get_queryset().filter(endDate__gt=start_date, endDate__lte=end_date).exists():
            return False
        return True


class Event(models.Model):
    name = models.CharField(max_length=64, null=True, blank=True)
    place = models.ForeignKey(to=Place, null=True, blank=True, on_delete=models.SET_NULL)
    startDate = models.DateField()
    endDate = models.DateField(null=True, blank=True)
    startTime = models.TimeField(null=True, blank=True)
    endTime = models.TimeField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    type = models.CharField(max_length=4, choices=Events.EVENT_TYPES)
    tak = models.CharField(max_length=3, null=True, blank=True, choices=Takken.TAKKEN)

    objects = models.Manager()
    rentals = RentManager()

    class Meta:
        ordering = ['startDate', 'startTime']

    def save(self, *args, **kwargs):
        if not self.endDate:
            self.endDate = self.startDate
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        fields = []
        if self.name:
            fields.append(str(self.name))
        if self.place:
            fields.append(str(self.place))
        if self.startDate:
            fields.append(str(self.startDate))
        if self.endDate:
            fields.append(str(self.endDate))
        if self.startTime:
            fields.append(str(self.startTime))
        if self.endTime:
            fields.append(str(self.endTime))
        if self.description:
            fields.append(self.description)
        if self.type:
            fields.append(str(self.get_type_display()))
        if self.tak:
            fields.append(str(self.get_tak_display()))
        return ', '.join(fields)

apps/agenda/views.py
from django.shortcuts import render

from apps.agenda.queries import get_vergaderingen, get_public_and_jincafe_events


def index(request, all_vergaderingen=False):
    vergaderingen = get_vergaderingen(all_vergaderingen=all_vergaderingen)
    events = get_public_and_jincafe_events()
    return render(request, 'agenda/index.html', {'title_suffix': ' - Agenda',
                                                 'events': events,
                                                 'vergaderingen': vergaderingen})

apps/agenda/templates/agenda/index.html
{% extends 'home/base.html' %}

{% block content %}
    <h1>Agenda</h1>
    <h2>Algemeen</h2>
    {# todo met annotations op model in query werken voor dates! if bij strings mogen weg #}
    {# todo de datum mooier maken, als het maar 1 dag is, geen twee keer weergeven #}
    {% for event in events %}
        <p>
            <b>{% if event.name %}{{ event.name }}</b> <br>{% endif %}
            {% if event.place %}{{ event.place }} <br>{% endif %}
            {% if event.startDate %}{{ event.startDate | date:"l" | capfirst }} {{ event.startDate }}{% endif %}{% if event.endDate %} - {{ event.startDate | date:"l" }} {{ event.endDate }} <br>{% endif %}
            {% if event.startTime %}{{ event.startTime }}{% endif %}
            {% if event.endTime %}- {{ event.endTime }} <br>{% endif %}
            {% if event.description %}{{ event.description }} <br>{% endif %}
        </p>
    {% endfor %}
    <h2>Vergaderingen</h2>
    <p>
        <a href="{% url 'agenda:index_all_vergaderingen' %}">Bekijk de afgelopen vergaderingen.</a>
    </p>
    {% for vergadering in vergaderingen %}
        <p>
            <b>{% if vergadering.tak %}{{ vergadering.get_tak_display }} - {% endif %}
                {% if vergadering.name %}{{ vergadering.name }}</b> <br>{% endif %}
            {% if vergadering.place %}{{ vergadering.place }} <br> {% endif %}
            {{ vergadering.startDate | date:"l" | capfirst }} {{ vergadering.startDate }}{% if vergadering.endDate %} - {{ vergadering.startDate | date:"l" }} {{ vergadering.endDate }} <br> {% endif %}
            {% if vergadering.startTime %}{{ vergadering.startTime }}{% endif %}
            {% if vergadering.endTime %} - {{ vergadering.endTime }} <br>{% endif %}
            {% if vergadering.description %}{{ vergadering.description }} <br>{% endif %}
        </p>
    {% endfor %}
{% endblock content %}