BosvogelWebPlatform/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('agenda/', include('apps.agenda.urls')),
                  path('leiding/', include('apps.leiding.urls')),
                  path('verhuur/', include('apps.rent.urls')),
                  path('takken/', include('apps.takken.urls')),
                  path('', include('apps.home.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/rent/urls.py
from django.urls import path

from . import views

app_name = 'rent'
urlpatterns = [
    path('', views.index, name='index'),
    path('beheer/', views.manage_rentals, name='manage_rentals'),
    path('fotos/', views.photos, name='photos'),
    path('gebouw_en_terrein/', views.building_and_terrain, name='building_and_terrain'),
    path('tarieven/', views.pricing, name='pricing'),
    path('tarieven_aanpassen/', views.change_pricing, name='change_pricing'),
    path('contracten/', views.contracts, name='contracts'),
    # todo make choice: contracts publicly available, or trough mail when reserved? Or via 'huishoudelijk regelement'?
    path('reserveren/', views.reserve, name='reserve'),
]

apps/rent/models.py
from django.db import models
from django.dispatch import receiver

from apps.agenda.models import Event
from apps.home.validators import validate_phone_number, validate_iban_format
from apps.place.models import Place


NEW_REQUEST = 'NR'
COMMUNICATING = 'CO'
AWAITING_CONTRACT = 'AC'
AWAITING_DEPOSIT = 'AD'
APPROVED = 'AP'
AWAITING_PAYMENT = 'AP'
CANCELLED = 'CA'
DONE = 'DO'

RESERVATION_STATUSES = (
    (NEW_REQUEST, 'Nieuwe aanvraag'),
    (COMMUNICATING, 'Communicatie gestart'),
    (AWAITING_CONTRACT, 'Wachten op contract'),
    (AWAITING_DEPOSIT, 'Wachten op storting voorschot'),
    (APPROVED, 'Goedgekeurd'),
    (AWAITING_PAYMENT, 'Afwachten betaling eindafrekening'),
    (CANCELLED, 'Afgezegd'),
    (DONE, 'Afgelopen'),
)

AWAITING = 'A'
DEPOSITED = 'D'
REFUNDED = 'R'

DEPOSIT_STATUSES = (
    (AWAITING, 'In afwachting'),
    (DEPOSITED, 'Gestort'),
    (REFUNDED, 'Terugbetaald')
)


# todo verboden maken om te verwijderen! of verwijderen blokkeren
class Pricing(models.Model):
    perPersonPerDay = models.DecimalField(max_digits=5, decimal_places=2)
    dailyMinimum = models.DecimalField(max_digits=5, decimal_places=2)
    electricitykWh = models.DecimalField(max_digits=5, decimal_places=2)
    waterSqM = models.DecimalField(max_digits=5, decimal_places=2)
    gasPerDay = models.DecimalField(max_digits=5, decimal_places=2)
    deposit = models.DecimalField(max_digits=5, decimal_places=2)
    pricesSetOn = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Tarieven'
        verbose_name_plural = 'Tarieven'

    def __str__(self):
        return 'Pricing (' + str(self.pricesSetOn) + ')'


class Reservation(models.Model):
    # todo add depositDeadline, add this in email, overviews, admin, crontab to send mails, ....
    groupName = models.CharField(max_length=64)
    town = models.CharField(max_length=32)
    email = models.EmailField()
    phoneNr = models.CharField(max_length=13, validators=[validate_phone_number])
    period = models.ForeignKey(null=True, to=Event, on_delete=models.SET_NULL)
    pricing = models.ForeignKey(null=True, to=Pricing, on_delete=models.SET_NULL)
    bankAccountNumber = models.CharField(max_length=19, validators=[validate_iban_format])
    contract = models.FileField(null=True, blank=True)  # todo pick destination
    status = models.CharField(max_length=3, choices=RESERVATION_STATUSES, default=NEW_REQUEST)
    depositStatus = models.CharField(max_length=1, choices=DEPOSIT_STATUSES, default=AWAITING)
    depositAmount = models.IntegerField(null=True, blank=True)
    numberOfPeople = models.IntegerField()
    checklist = models.TextField(null=True, blank=True)  # todo convert to jsonb?
    finalBill = models.DecimalField(null=True, blank=True, max_digits=5, decimal_places=2)
    comments = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Reservatie'
        verbose_name_plural = 'Reservaties'

    def __str__(self):
        if self.period:
            return self.groupName + ' (' + self.town + '), ' + str(self.period.startDate) + ' - ' + str(
                self.period.endDate)
        return self.groupName + ' (' + self.town + ')'


@receiver(models.signals.post_delete, sender=Reservation)
def handle_deleted_reservation(sender, instance, **kwargs):
    if instance.period:
        instance.period.delete()

apps/rent/forms.py
import datetime

from django import forms

from apps.agenda.models import Event
from apps.rent.models import Reservation, Pricing


# noinspection PyPep8Naming
from apps.rent.queries import get_prices


class ReservationForm(forms.ModelForm):

    startDate = forms.DateField(widget=forms.SelectDateWidget,
                                required=True,
                                label='Huren van')
    endDate = forms.DateField(widget=forms.SelectDateWidget,
                              required=True,
                              label='Huren tot')

    class Meta:
        model = Reservation
        fields = [
            'groupName',
            'town',
            'email',
            'phoneNr',
            'bankAccountNumber',
            'startDate',
            'endDate',
            'numberOfPeople',
            'comments'
        ]
        labels = {
            'groupName': 'Groepsnaam',
            'town': 'Gemeente',
            'email': 'E-mail',
            'phoneNr': 'GSM nummer',
            'bankAccountNumber': 'Rekeningnummer',
            'numberOfPeople': 'Aantal personen (schatting)',
            'comments': 'Extra commentaar of vragen',
        }
        help_texts = {
            'email': 'Gebruik een zo algemeen mogelijk email adres, vb: info@organisatie.be',
        }

    def clean(self):
        data = super().clean()

        startDate = data.get('startDate')
        endDate = data.get('endDate')

        if startDate is None or endDate is None:
            raise forms.ValidationError('Gelieve een start- en einddatum aan te duiden')

        if startDate < datetime.date.today():
            raise forms.ValidationError('Gelieve een datum in de toekomst aan te duiden')
        if startDate.month not in [6, 7, 8, 9]:  # june, july, august, and september
            raise forms.ValidationError('Het is enkel mogelijk om tijdens de zomervakantie te huren')
        if endDate < datetime.date.today():
            raise forms.ValidationError('Gelieve een datum in de toekomst aan te duiden')
        if endDate.month not in [6, 7, 8, 9]:  # june, july, august, and september
            raise forms.ValidationError('Het is enkel mogelijk om tijdens de zomervakantie te huren')

        if startDate > endDate:
            raise forms.ValidationError('De einddatum moet na de startdatum komen')

        if not Event.rentals.is_available_for_rent(startDate, endDate):
            raise forms.ValidationError('Deze periode is niet volledig vrij om te huren')


class PricingForm(forms.ModelForm):
    class Meta:
        model = Pricing
        fields = [
            'perPersonPerDay',
            'dailyMinimum',
            'electricitykWh',
            'waterSqM',
            'gasPerDay',
            'deposit',
        ]
        labels = {
            'perPersonPerDay': 'Per persoon per dag',
            'dailyMinimum': 'Minimum dagelijks bedrag',
            'electricitykWh': 'Electriciteitsprijs per kWh',
            'waterSqM': 'Waterprijs per m³',
            'gasPerDay': 'Gasprijs per dag',
            'deposit': 'Waarborg',
        }
        help_texts = {
            'dailyMinimum': 'Minimale dagprijs berekend op enkel het aantal personen.',
        }

    def clean(self):
        data = super().clean()
        current_prices = get_prices()
        if current_prices.perPersonPerDay == data.get('perPersonPerDay') and current_prices.dailyMinimum == \
                data.get('dailyMinimum') and current_prices.electricitykWh == data.get('electricitykWh') and \
                current_prices.waterSqM == data.get('waterSqM') and current_prices.gasPerDay == \
                data.get('gasPerDay') and current_prices.deposit == data.get('deposit'):
            raise forms.ValidationError('Geen verschil met de vorige tarieven.')

apps/rent/views.py
from django.contrib import messages
from django.core import mail
from django.shortcuts import render, redirect
from django.urls import reverse
from rules.contrib.views import permission_required

from BosvogelWebPlatform import settings
from BosvogelWebPlatform.settings import EMAIL_ADDRESS_RENT, EMAIL_ADDRESS_NOREPLY
from apps.agenda.models import Event
from apps.rent.forms import ReservationForm, PricingForm
from apps.rent.models import Reservation, Pricing
from apps.rent.queries import get_prices


def index(request):
    return render(request, 'rent/index.html', {'title_suffix': ' - Verhuur'})


@permission_required('rent.access_rent_management')  # todo test access
def manage_rentals(request):  # todo test  perofrmance objects.select_related()
    return render(request, 'rent/manage_rentals.html', {'title_suffix': ' - Beheer',
                                                        'rentals': Reservation.objects.all()})


def photos(request):
    return render(request, 'rent/photos.html', {'title_suffix': ' - Verhuur Foto\'s'})


def building_and_terrain(request):
    return render(request, 'rent/building_and_terrain.html', {'title_suffix': ' - Gebouw & Terrein'})


def pricing(request):
    current_prices = get_prices()
    if current_prices.perPersonPerDay == 0:
        mail.send_mail('ERROR - Verhuur prijzen zijn nog niet gezet!',  # todo better test this mail
                       'Iemand bekeek de huurprijzen (die nog niet zijn ingesteld), \n'
                       + 'zolang er geen verhuurpijzen ingesteld zijn is het onmogelijk om reservaties te maken.\n'
                       + 'Surf zo snel mogelijk naar onderstaande link om de verhuurtarieven in te stellen:\n'
                       + request.build_absolute_uri(reverse('rent:change_pricing')),
                       from_email=EMAIL_ADDRESS_NOREPLY,
                       recipient_list=[EMAIL_ADDRESS_RENT])  # todo add group leaders
    return render(request, 'rent/pricing.html', {'title_suffix': ' - Tarieven',
                                                 'price': current_prices})


@permission_required('rent.change_pricing')
def change_pricing(request):
    if request.method == 'POST':
        form = PricingForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Verhuurtarieven aangepast')
            new_prices = Pricing.objects.order_by('-pricesSetOn')[0]
            if Pricing.objects.count() > 1:
                prev = Pricing.objects.order_by('-pricesSetOn')[1]
            else:
                prev = Pricing(
                    perPersonPerDay=0,
                    dailyMinimum=0,
                    electricitykWh=0,
                    waterSqM=0,
                    gasPerDay=0,
                    deposit=0)
            mail.send_mail('Opgelet, de verhuurpijzen zijn aangepast.',
                           f'De verhuurtarieven zijn aangepast door {request.user}. De nieuwe prijzen zijn :\n'
                           + f'Per persoon per dag: \t€ {prev.perPersonPerDay} --> € {new_prices.perPersonPerDay}\n'
                           + f'Dagelijks minimum \t\t€ {prev.dailyMinimum} --> € {new_prices.dailyMinimum}\n'
                           + f'Electriciteit per kWh: \t€ {prev.electricitykWh} --> € {new_prices.electricitykWh}\n'
                           + f'Water per m³: \t\t\t€ {prev.waterSqM} --> € {new_prices.waterSqM}\n'
                           + f'Gas per dag: \t\t\t€ {prev.gasPerDay} --> € {new_prices.gasPerDay}\n'
                           + f'Waarborg: \t\t\t\t€ {prev.deposit} --> € {new_prices.deposit}\n'
                           + 'Surf naar '
                           + request.build_absolute_uri(reverse('rent:change_pricing'))
                           + ' om ze aan te passen als dit een fout was.',
                           from_email=EMAIL_ADDRESS_NOREPLY,  # todo better test this mail
                           recipient_list=[EMAIL_ADDRESS_RENT])  # todo when user app finished send to grl
            return redirect('rent:pricing')
    else:
        form = PricingForm(instance=get_prices())
    return render(request, 'rent/change_pricing.html', {'title_suffix': ' - Verhuur', 'form': form})


def contracts(request):
    return render(request, 'rent/contracts.html', {'title_suffix': ' - Verhuurcontract'})


# todo verhuur

# transacties apart bijhouden
# op basis van de transacties (onsave) de status aanpassen
# nakijken van bedrag betaald etc.
# Dit volledig uischrijven en op issue zetten
# event sourced maken van de te betalen/betalen bedragen
# workflow uittekenen (en bij admins laten zien?)


def reserve(request):
    if request.method == 'POST':
        # todo dit refactorren: niet zo vragen, maar via get_prices() doen, dan moet er ook gelogd worden!
        if not Pricing.objects.all().exists():
            messages.warning(request, 'Reserveren tijdelijk niet mogelijk.')
            # todo use the same template as in the pricing view
            mail.send_mail(f'ERROR - Verhuur prijzen zijn nog niet gezet!',
                           'Iemand probeerde het lokaal te huren, \n'
                           + 'maar zolang er geen verhuurpijzen ingesteld zijn '
                           + 'is het onmogelijk om reservaties te maken.\n'
                           + 'Surf zo snel mogelijk naar onderstaande link om de verhuurtarieven in te stellen:\n'
                           + request.build_absolute_uri(reverse('rent:change_pricing')),
                           EMAIL_ADDRESS_NOREPLY,
                           [EMAIL_ADDRESS_RENT])  # todo add grl
            return redirect('rent:index')
        form = ReservationForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data

            rent_event = Event.rentals.new_rental(
                form_data['startDate'],
                form_data['endDate'],
                'Verhuur - ' + form_data['groupName'])

            reservation = form.save(commit=False)
            reservation.pricing = get_prices()
            reservation.period = rent_event
            reservation.save()

            messages.success(request, 'Reservatie gelukt! Check je mailbox voor meer informatie.')
            # todo richer email body through template
            # todo add contract as attachment
            mail.send_mail(f'Scouts Bosvogels - Verhuur {reservation.groupName}, '
                           f'{reservation.period.startDate} - {reservation.period.endDate}',
                           'Nieuwe reservatie',
                           EMAIL_ADDRESS_RENT,
                           [reservation.email])
            # todo richer email body through template
            mail.send_mail(f'Nieuwe verhuuraanvraag - {reservation.groupName}, '
                           f'{reservation.period.startDate} - {reservation.period.endDate}',
                           'Nieuwe verhuuraanvraag',
                           EMAIL_ADDRESS_NOREPLY,
                           [EMAIL_ADDRESS_RENT])

            return redirect(
                'rent:reserve')  # todo na geslaagde reservatie niet terug uitkomen op de form, is verwarrend
    else:  # todo remove after finishing development
        if settings.DEBUG:  # pragma: no cover
            if Event.rentals.all().exists():
                end = Event.rentals.latest('endDate').endDate
                form = ReservationForm(initial={
                    'groupName': 'Testgroup',
                    'town': 'TestTown',
                    'email': 'test@test.text',
                    'phoneNr': '0471589589',
                    'bankAccountNumber': 'BE24 2222 2222 2222',
                    'numberOfPeople': '50',
                    'comments': 'Hey how hey! test test test test',
                    'startDate': f'{end.day}-{end.month}-{end.year}',
                    'endDate': f'{end.day + 1}-{end.month}-{end.year}'
                })
            else:
                form = ReservationForm(initial={
                    'groupName': 'Testgroup',
                    'town': 'TestTown',
                    'email': 'test@test.text',
                    'phoneNr': '0471589589',
                    'bankAccountNumber': 'BE24 2222 2222 2222',
                    'numberOfPeople': '50',
                    'comments': 'Hey how hey! test test test test',
                })
        else:  # pragma: no cover
            form = ReservationForm()
    return render(request, 'rent/reserve.html', {'title_suffix': ' - Reserveren', 'form': form})

apps/rent/templates/rent/building_and_terrain.html
{% extends 'rent/rent_base.html' %}

{% block content %}
    <h1>Verhuur gebouw en terrein pagina!</h1>
{% endblock content %}

apps/rent/templates/rent/change_pricing.html
{% extends 'rent/rent_base.html' %}

{% block content %}
    <h1>Tarieven aanpassen</h1>
    <form action="{% url 'rent:change_pricing' %}" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Wijzig tarieven">
    </form>
{% endblock content %}

apps/rent/templates/rent/contracts.html
{% extends 'rent/rent_base.html' %}

{% block content %}
    <h1>Verhuur contract pagina!</h1>
{% endblock content %}

apps/rent/templates/rent/index.html
{% extends 'rent/rent_base.html' %}

{% block content %}
    <h1>Verhuur home pagina!</h1>
    <p>De Rimboe is niet te huur voor weekends. Wij verhuren onze lokalen maximaal 60 dagen per jaar (tijdens de
        zomermaanden) en enkel aan georganiseerde jeugdgroepen.</p>

    <p>Het kampterrein "De Rimboe" behoort tot de plaatselijke scoutsgroep "De Bosvogels" en staat enkel tijdens de
        zomermaanden open voor alle jeugdverenigingen. Tijdens het jaar is het praktisch onmogelijk om De Rimboe te
        huren. Er mag naar hartenlust geravot worden. Toch is het belangrijk dat iedereen respect opbrengt voor de
        lokalen, het aanwezige materiaal en de omgeving. We vragen dus om het nodige respect te hebben met onze geliefde
        Rimboe.

        Het kampterrein bestaat uit 2 gebouwen: het 'Groot lokaal' en het 'Klein lokaal'. In het grote gebouw zijn 3
        slaaplokalen beschikbaar. Er is een volledig uitgeruste keuken voor maximum 60 personen met grote oven, ijskast,
        diepvrieskist, potten, pannen, borden, bestek, etc. Grotere groepen kunnen ook in het lokaal verblijven, maar
        moeten dan zelf extra gerief meebrengen. Er zijn 6 toiletten en een gemeenschappelijke douche. Het kleine gebouw
        bestaat uit 3 lokalen en een sanitair gedeelte met 3 toiletten.

        Alle bossen rond "De Rimboe" zijn eigendom van Natuurpunt en zijn enkel toegankelijk via de bospaden. Enkel de
        aangewezen bossen mag als speelbos gebruikt worden. Kampvuur is toegelaten, maar enkel op de kampvuurplaats.
        Alle kampvuurresten dienen volledig verwijderd te worden.

        Meer informatie over de lokalen vind je verder op onze site en in het document 'Verhuurreservering Rimboe'.

        Heb je interesse in huur van ons lokaal? Kijk dan eerst of het lokaal beschikbaar is. Lees daarna het het
        document 'Verhuurreservering Rimboe' door. Vul dit document in en neem dan vrijblijvend contact op met
        verhuur@bosvogels.be. Voeg het ingevulde document 'Verhuurreservering Rimboe' toe als bijlage.
        Bij goedkeuring zal de verhuurverantwoordelijke de gewenste periode op de kalender aanduiden als bezet. Pas
        wanneer dit gebeurd is, is de reservatie rond. Controleer daarom goed dat je afgesproken huurperiode is
        aangeduid op de beschikbaarheid!!! Verwittig de verhuurverantwoordelijke indien nodig.</p>

    <iframe src="https://www.google.com/maps/d/embed?mid=12-yXKMTjn0QiTp7gEYEqyZyl4xs" width="640"
            height="480"></iframe>

{% endblock content %}

apps/rent/templates/rent/manage_rentals.html
{% extends 'rent/rent_base.html' %}

{% block content %}
    <h1>Verhuur management pagina!</h1>

    <a href="{% url 'rent:change_pricing' %}">
        <button>Pas verhuurpijzen aan</button>
    </a>

{% endblock content %}

apps/rent/templates/rent/photos.html
{% extends 'rent/rent_base.html' %}

{% block content %}
    <h1>Verhuur foto's pagina!</h1>
{% endblock content %}

apps/rent/templates/rent/pricing.html
{% extends 'rent/rent_base.html' %}

{% block content %}
    <h1>Tarieven</h1>
    <p>
        Dit zijn de tarieven die momenteel gebruikt worden. Let wel, deze zijn ter illustratie.
        In het verhuurcontract staan de werkelijke prijzen, maar deze zullen hier amper of niet van verschillen.
    </p>

    <ul>
        <li>€ {{ price.perPersonPerDay }} per persoon, per dag met een minimum van € {{ price.dailyMinimum }} per dag
        </li>
        <li>€ {{ price.electricitykWh }} per kWh verbruikte elektriciteit (oven, microgolfoven, koelkast, vriezer,
            verlichting, ...)
        </li>
        <li>€ {{ price.waterSqM }} per m³ water (douches, wc's, gootsteen, ...)</li>
        <li>€ {{ price.gasPerDay }} per dag voor gas (verwarming, douches, kookvuur, ...)</li>
        <li>€ {{ price.deposit }} waarborg</li>
    </ul>
    {# todo simple prijscalculator inplementeren #}
{% endblock content %}

apps/rent/templates/rent/rent_base.html
{% extends 'home/base.html' %}
{% load rules %}


{% block links %}
    {% has_perm 'rent.access_rent_management' user as can_access_rent_management %}
    <h2>Verhuur links:</h2>
    <ul>
        <li><a href="{% url 'rent:index' %}">Algmeen</a></li>
        {% if can_access_rent_management %}
            <li><a href="{% url 'rent:manage_rentals' %}">Beheer</a></li>{% endif %}
        <li><a href="{% url 'rent:building_and_terrain' %}">Gebouw en terrein</a></li>
        <li><a href="{% url 'rent:photos' %}">Foto's</a></li>
        <li><a href="{% url 'rent:pricing' %}">Tarieven</a></li>
        <li><a href="{% url 'rent:contracts' %}">Contracten</a></li>
        <li><a href="{% url 'rent:reserve' %}">Reserveren</a></li>
    </ul>
{% endblock links %}

apps/rent/templates/rent/rent_home.html
{% extends 'rent/rent_base.html' %}

{% block content %}
    <h1>Verhuur home pagina!</h1>
    <p>De Rimboe is niet te huur voor weekends. Wij verhuren onze lokalen maximaal 60 dagen per jaar (tijdens de
        zomermaanden) en enkel aan georganiseerde jeugdgroepen.</p>

    <p>Het kampterrein "De Rimboe" behoort tot de plaatselijke scoutsgroep "De Bosvogels" en staat enkel tijdens de
        zomermaanden open voor alle jeugdverenigingen. Tijdens het jaar is het praktisch onmogelijk om De Rimboe te
        huren. Er mag naar hartenlust geravot worden. Toch is het belangrijk dat iedereen respect opbrengt voor de
        lokalen, het aanwezige materiaal en de omgeving. We vragen dus om het nodige respect te hebben met onze geliefde
        Rimboe.

        Het kampterrein bestaat uit 2 gebouwen: het 'Groot lokaal' en het 'Klein lokaal'. In het grote gebouw zijn 3
        slaaplokalen beschikbaar. Er is een volledig uitgeruste keuken voor maximum 60 personen met grote oven, ijskast,
        diepvrieskist, potten, pannen, borden, bestek, etc. Grotere groepen kunnen ook in het lokaal verblijven, maar
        moeten dan zelf extra gerief meebrengen. Er zijn 6 toiletten en een gemeenschappelijke douche. Het kleine gebouw
        bestaat uit 3 lokalen en een sanitair gedeelte met 3 toiletten.

        Alle bossen rond "De Rimboe" zijn eigendom van Natuurpunt en zijn enkel toegankelijk via de bospaden. Enkel de
        aangewezen bossen mag als speelbos gebruikt worden. Kampvuur is toegelaten, maar enkel op de kampvuurplaats.
        Alle kampvuurresten dienen volledig verwijderd te worden.

        Meer informatie over de lokalen vind je verder op onze site en in het document 'Verhuurreservering Rimboe'.

        Heb je interesse in huur van ons lokaal? Kijk dan eerst of het lokaal beschikbaar is. Lees daarna het het
        document 'Verhuurreservering Rimboe' door. Vul dit document in en neem dan vrijblijvend contact op met
        verhuur@bosvogels.be. Voeg het ingevulde document 'Verhuurreservering Rimboe' toe als bijlage.
        Bij goedkeuring zal de verhuurverantwoordelijke de gewenste periode op de kalender aanduiden als bezet. Pas
        wanneer dit gebeurd is, is de reservatie rond. Controleer daarom goed dat je afgesproken huurperiode is
        aangeduid op de beschikbaarheid!!! Verwittig de verhuurverantwoordelijke indien nodig.</p>

    <iframe src="https://www.google.com/maps/d/embed?mid=12-yXKMTjn0QiTp7gEYEqyZyl4xs" width="640"
            height="480"></iframe>

{% endblock content %}

apps/rent/templates/rent/reserve.html
{% extends 'rent/rent_base.html' %}

{% block content %}
    <h1>Verhuur reservatie pagina!</h1>
{% endblock content %}