BosvogelWebPlatform/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('agenda/', include('apps.agenda.urls')),
                  path('leiding/', include('apps.leiding.urls')),
                  path('verhuur/', include('apps.rent.urls')),
                  path('takken/', include('apps.takken.urls')),
                  path('', include('apps.home.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/agenda/urls.py
from django.urls import path

from . import views

app_name = 'agenda'
urlpatterns = [
    path('', views.index, name='index'),
    path('alle-vergaderingen', views.index, {'all_vergaderingen': 'True'}, name='index_all_vergaderingen')
]

apps/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

apps/leiding/urls.py
from django.urls import path

from . import views

app_name = 'leiding'
urlpatterns = [
    path('', views.index, name='index'),
]

apps/rent/urls.py
from django.urls import path

from . import views

app_name = 'rent'
urlpatterns = [
    path('', views.index, name='index'),
    path('beheer/', views.manage_rentals, name='manage_rentals'),
    path('fotos/', views.photos, name='photos'),
    path('gebouw_en_terrein/', views.building_and_terrain, name='building_and_terrain'),
    path('tarieven/', views.pricing, name='pricing'),
    path('tarieven_aanpassen/', views.change_pricing, name='change_pricing'),
    path('contracten/', views.contracts, name='contracts'),
    # todo make choice: contracts publicly available, or trough mail when reserved? Or via 'huishoudelijk regelement'?
    path('reserveren/', views.reserve, name='reserve'),
]

apps/takken/urls.py
from django.urls import path

from . import views

app_name = 'takken'
urlpatterns = [
    path('', views.index, name='index'),
    path('wat-na-leiding/', views.afterleader, name='afterleader'),
    path('<slug:tak>/', views.tak_overview, name='tak'),
    path('<slug:tak>/alle-vergaderingen', views.tak_overview, {'all_vergaderingen': 'True'}
         , name='tak_all_vergaderingen'),
]

apps/home/models.py
import logging
from datetime import date

from django.db import models

from utils.model_utils import OverwriteOnSameNameStorage

logger = logging.getLogger(__name__)


def get_yeartheme_logo_path(instance, filename):
    filename_extension = filename.split('.')[-1]
    return f'img/jaarthema/logo_jaarthema_{instance.year}-{instance.year-1}.{filename_extension}'


def get_workyear(now=date.today()):  # todo wouter tests naar hier laten wijzen
    september_first = date(now.year, 9, 1)
    year = now.year
    if now < september_first:
        year -= 1
    return year


class WerkjaarManager(models.Manager):
    def current_year(self, now=date.today()): # todo wouter alles dat dit gebruikt en enkel het jaar nodig heeft de get_workyear laten pakken
        werkjaar, created = self.get_or_create(year=get_workyear(now))
        if created:
            logger.warning(f'Werkjaar.objects.current_year is called for {now},'
                           f' which did not exist so a new one is created')
        return werkjaar

    def last_year(self, now=date.today()):
        return self.current_year(now).previous_year()


class Werkjaar(models.Model):
    year = models.IntegerField(unique=True)
    yearTheme = models.CharField(blank=True, max_length=255)
    yearThemeLogo = models.ImageField(blank=True,
                                      storage=OverwriteOnSameNameStorage(),
                                      upload_to=get_yeartheme_logo_path)
    yearThemeSong = models.URLField(blank=True)

    objects = WerkjaarManager()

    def __str__(self):
        return str(self.year) + " - " + str(self.year + 1)

    class Meta:
        verbose_name_plural = 'Werkjaren'
        ordering = ['-year']

    def next_year(self):
        werkjaar, created = Werkjaar.objects.get_or_create(year=self.year + 1)
        if created:
            logger.warning(f'A new werkjaar object was created for werkjaar {werkjaar.year} - {werkjaar.year + 1} '
                           f'due to calling werkjaar.next_year()')
        return werkjaar

    def previous_year(self):
        werkjaar, created = Werkjaar.objects.get_or_create(year=self.year - 1)
        if created:
            logger.warning(f'A new werkjaar object was created for werkjaar {werkjaar.year} - {werkjaar.year + 1} '
                           f'due to calling werkjaar.previous_year()')
        return werkjaar

apps/home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/landing.html', {'title_suffix': ' - Home'})

apps/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>De Bosvogels{{ title_suffix }}</title>
    <link rel="shortcut icon" href="{%  static 'home/img/favicon.png' %}">
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/light.css'>{# todo remove #}
</head>
<body>

{% if debug %}
    <h3 style="color:orange;background-color: white">Warning: Django debug is True. This message should never be seen in Production!</h3>
{% endif %}

{# Navbar style navigation trough the website #}
{% block navbar %}
    <ul>
        <li><a href="{% url 'home:index' %}">Home/Landing</a></li>
        <li><a href="{% url 'agenda:index' %}">Agenda</a></li>
        <li><a href="{% url 'leiding:index' %}">Leiding</a></li>
        <li><a href="{% url 'takken:index' %}">Takken</a></li>
        <li><a href="{% url 'rent:index' %}">Verhuur</a></li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li> {# todo remove #}
    </ul>
{% endblock navbar %}

{# Block for links to the sub pages#}
{% block links %}{% endblock links %}

{# Messages #}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}"><b>{{ message }}</b></li>
        {% endfor %}
    </ul>
{% endif %}

{#  Main content for the page #}
{% block content %}{% endblock content %}

{# Custom JS scripts #}
{% block javascript %}{% endblock javascript %}

</body>
</html>

apps/home/templates/home/landing.html
{% extends 'home/base.html' %}

{% block content %}
    <h1>Welcome at the landing page!</h1>
{% endblock content %}