BosvogelWebPlatform/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('agenda/', include('apps.agenda.urls')),
                  path('leiding/', include('apps.leiding.urls')),
                  path('verhuur/', include('apps.rent.urls')),
                  path('takken/', include('apps.takken.urls')),
                  path('', include('apps.home.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/takken/urls.py
from django.urls import path

from . import views

app_name = 'takken'
urlpatterns = [
    path('', views.index, name='index'),
    path('wat-na-leiding/', views.afterleader, name='afterleader'),
    path('<slug:tak>/', views.tak_overview, name='tak'),
    path('<slug:tak>/alle-vergaderingen', views.tak_overview, {'all_vergaderingen': 'True'}
         , name='tak_all_vergaderingen'),
]

apps/takken/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from apps.agenda.queries import get_vergaderingen
from apps.home.constants import Takken
from apps.profile.queries import get_active_leader_memberships


def index(request):
    return render(request, 'takken/index.html', {'title_suffix': ' - Takken'})


def tak_overview(request, tak, all_vergaderingen=False):
    # todo refactor this part
    found = False
    takinfos = [Takken.TAKINFO_KAP, Takken.TAKINFO_WEL, Takken.TAKINFO_KAB, Takken.TAKINFO_JV, Takken.TAKINFO_JG,
                Takken.TAKINFO_V, Takken.TAKINFO_G, Takken.TAKINFO_JIN, Takken.TAKINFO_L, Takken.TAKINFO_GRL]
    found_takinfo = None
    for takinfo in takinfos:
        if takinfo['fullName'].lower() == tak.lower():
            found = True
            found_takinfo = takinfo
            break
    if not found:
        return redirect(reverse('takken:index'))

    memberships = get_active_leader_memberships(found_takinfo['abbrev'])

    vergaderingen = get_vergaderingen(found_takinfo['abbrev'], all_vergaderingen)

    context = {'title_suffix': ' -  ' + found_takinfo['fullName'],
               'tak': found_takinfo['fullName'],
               'takabbreviation': found_takinfo['abbrev'],
               'taklogo': found_takinfo['takteken'],
               'age': found_takinfo['age'],
               'description': found_takinfo['description'],
               'memberships': memberships,
               'vergaderingen': vergaderingen}

    if 'takmail' in found_takinfo:
        context['takmail'] = found_takinfo['takmail']

    return render(request, 'takken/takview.html', context)


def afterleader(request):
    return render(request, 'takken/takken_afterleader.html', {'title_suffix': ' -  Wat na leiding?',
                                                              'tak': 'Wat na leiding?'})

apps/takken/templates/takken/index.html
{% extends 'takken/takken_base.html' %}

{% block content %}
    <h1>index pagina takken!</h1>

    <h2>Hier algemene info enzo!</h2>
{% endblock content %}

apps/takken/templates/takken/takken_afterleader.html
{% extends 'takken/takken_base.html' %}
{% load static %}

{% block content %}
   {# Todo add content #}
    Hier statische info over wat je kan doen na de leiding
    Uitleg over district, gouw, verbond met overal contactgegevens etc erbij
{% endblock content %}

apps/takken/templates/takken/takken_base.html
{% extends 'home/base.html' %}

{% block links %}
    <h2>Takken links:</h2>
    <ul>
        <li><a href="{% url 'takken:tak' 'kapoenen' %}">Kapoenen</a></li>
        <li><a href="{% url 'takken:tak' 'kabouters' %}">Kabouters</a></li>
        <li><a href="{% url 'takken:tak' 'welpen' %}">Welpen</a></li>
        <li><a href="{% url 'takken:tak' 'jonggidsen' %}">Jonggidsen</a></li>
        <li><a href="{% url 'takken:tak' 'jongverkenners' %}">Jongverkenners</a></li>
        <li><a href="{% url 'takken:tak' 'gidsen' %}">Gidsen</a></li>
        <li><a href="{% url 'takken:tak' 'verkenners' %}">Verkenners</a></li>
        <li><a href="{% url 'takken:tak' 'jins' %}">Jins</a></li>
        <li><a href="{% url 'takken:tak' 'leiding' %}">Leiding</a></li>
        <li><a href="{% url 'takken:tak' 'groepsleiding' %}">Groepsleiding</a></li>
        <li><a href="{% url 'takken:afterleader' %}">Wat na leiding?</a></li>
    </ul>
{% endblock links %}

{% block content %}

{% endblock content %}

apps/takken/templates/takken/takview.html
{% extends 'takken/takken_base.html' %}
{% load static %}

{% block content %}
    <h1>Pagina van de {{ tak|lower }}!</h1>

    <h2>Leeftijd ({{ age }} jaar)</h2>
    <p>{{ description }}</p>
    {% if tak != "Leiding" %}
        <h2>Leiding</h2>
        {% if takmail %}<a href="mailto:{{ takmail }}">Mail naar {{ takmail }}</a>{% endif %}
        {% for membership in memberships %}
            <p>
                {{ membership.leader_name }}
                {% if membership.profile.public_email %}
                    <a href="mailto:{{ membership.profile.public_email }}">Mail
                        naar {{ membership.profile.public_email }}</a>
                {% endif %}
            </p>
        {% endfor %}
    {% endif %}
    {% if tak != "Groepsleiding" and tak != "Leiding" %}
        <h2>Vergaderingen</h2>
        <p>
            <a href="{% url 'takken:tak_all_vergaderingen' tak|lower %}">Bekijk de afgelopen vergaderingen.</a>
        </p>
        {% for vergadering in vergaderingen %}
            <p>
                <b>
                    {% if vergadering.name %}
                        {{ vergadering.name }}
                    {% else %}
                        Vergadering
                    {% endif %}
                </b>
                <br>
                {% if vergadering.place %}
                    {{ vergadering.place }} <br>
                {% endif %}
                {{ vergadering.startDate | date:"l" | capfirst }} {{ vergadering.startDate }}{% if vergadering.endDate %} - {{ vergadering.endDate | date:"l" }} {{ vergadering.endDate }}{% endif %}
                <br>

                {% if vergadering.startTime %}{{ vergadering.startTime }}{% endif %}{% if vergadering.endTime %}- {{ vergadering.endTime }} <br>{% endif %}

                {% if vergadering.description %}
                    {{ vergadering.description }} <br>
                {% endif %}
            </p>
        {% empty %}
            <p>Momenteel nog geen vergaderingen gepland!</p>
        {% endfor %}
    {% endif %}
    <img src="{% static taklogo %}" alt="Takteken {{ tak }}">
{% endblock content %}